### ISSUE TITLE
error x4509

### ISSUE THREAD

**Issue by AlexeyMatskevich** [murchalloo/murchFX#1]
Hello, thanks for the plugin, I tried to use your shader `DepthToAddon.fx` according to the README from https://github.com/murchalloo/reshade-addons. Since I don't know how to put shaders and I didn't find information in the guide, I just copied it to the folder with the reshade shaders. 

When running the program, reshade reports an error: "error X4509: maximum constant register index exceeded, target has 224 slots, manual bind to slot c254 failed".

Can you please tell me how to deal with it?

**Comment by murchalloo** [comment]
Everything works fine for me with latest 5.6 reshade version.
Can you tell how many other shaders is loaded also? You probably reach out the limit. You can remove some unnecessary shaders you don't use, that should help with this issue.

**Comment by AlexeyMatskevich** [comment]
I have tried loading just one your shaders, see ls
```shell
/reshade-shaders/Shaders
❯ ls -l
-rwxr--r-- 1 alex alex 18872 Nov 27 12:15 Blending.fxh
-rwxr--r-- 1 alex alex  4027 Feb 22 17:38 DepthToAddon.fx
-rwxr--r-- 1 alex alex  9359 Nov 27 12:15 DrawText.fxh
-rwxr--r-- 1 alex alex 21411 Nov 27 12:15 Macros.fxh
-rwxr--r-- 1 alex alex  3908 Nov 27 12:15 ReShade.fxh
-rwxr--r-- 1 alex alex 14148 Nov 27 12:15 ReShadeUI.fxh
-rwxr--r-- 1 alex alex  3475 Nov 27 12:15 TriDither.fxh
```
and with standard shaders: `Daltonize.fx  Deband.fx  DisplayDepth.fx  LUT.fx  UIMask.fx`
I was looking at the shaders in path from `ReShade.ini` setting -
`EffectSearchPaths=.\reshade-shaders\Shaders`

I use latest 5.6 `reshade with full add-on support`

**Comment by AlexeyMatskevich** [comment]
Maybe it's because I'm using it with an old game that's use DirectX9.

**Comment by AlexeyMatskevich** [comment]
I would like to write my own version of depth shader, but my programming skills it's web development on ruby language, and it's not relevant for that...

**Comment by AlexeyMatskevich** [comment]
I tried to find where reshade stores logs, but all I found was this:
![изображение](https://user-images.githubusercontent.com/45947106/220983254-ee1f5ac6-e86d-4241-aff0-db831885c168.png)

Full message: `error X4509: maximum constant register index exceeded, target has 224 slots, manual bind to slot c254 failed`

**Comment by AlexeyMatskevich** [comment]
I tried asking ChatGPT, and he said this:
```text
error X4509: maximum constant register index exceeded,
target has 224 slots, manual bind to slot c254 failed" error occurs
when the number of constant registers used in the shader
exceeds the maximum value available for that target
(224 registers for DirectX 9 and DirectX 10, 256 registers for DirectX 11).

In this case the problem may be caused by using the #include "ReShade.fxh" directive. 
This directive can extend to a large number of constant values which may cause 
exceeding the maximum number of constant registers.
```

**Comment by AlexeyMatskevich** [comment]
I found a workaround.  With https://github.com/doitsujin/dxvk I got the program to work using DirectX 11 and everything compiled, so definitely the problem was in the DirectX version. But frame_capture addon cannot load with 193 error.

**Comment by AlexeyMatskevich** [comment]
Hello?

**Comment by AlexeyMatskevich** [comment]
Since the author does not respond, I assume that the project is abandoned, and close issue.

**Comment by murchalloo** [comment]
Actually yeah, i don't work on it anymore, i just built a working version for my case and published source so someone may find it useful for the next projects.
